export const categoryNameSelected = {
  clothes: "clothes",
  electronics: "electronics",
  "women's%20clothing": "women's clothing",
  "men's%20clothing": "men's clothing",
  jewelery: "jewelery",
  // "sports and outdoors": "deportes y exteriores",
  // "jewelry and watches": "relojes y joyeria",
  // furniture: "muebles",
  // shoes: "zapatos",
  // fruits: "frutas",
  // "toys and games": "juegos y juguetes",
  // "home and kitchen": "casa y cocina",
  // "health and beauty": "salud y belleza",
  // "books and media": "libros y media",
};
